---
resources:
- name: repo
  type: git
  source:
    uri: https://github.com/mayuri-dhote/node-hello.git
    branch: main
jobs:
  - name: node-hello
    plan:
    - get: repo
      trigger: true
    - task: install
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: {repository: node}
        inputs:
         - name: repo
        outputs:
          - name: dependencies
        run:
            path: npm
            args:
            - pack
            - repo